"use client";

import { motion } from "framer-motion";
import { useResearchStore } from "@/store/useResearchStore";
import { InvestmentVerdictCard } from "./InvestmentVerdictCard";
import { OverviewCard } from "./OverviewCard";
import { FinancialMetricsGrid } from "./FinancialMetricsGrid";
import { NewsPanel } from "./NewsPanel";
import { SwotGrid } from "./SwotGrid";
import { RiskPanel } from "./RiskPanel";
import { BullBearBoard } from "./BullBearBoard";

export function ReportDashboard() {
  const { report } = useResearchStore();

  if (!report) return null;

  return (
    <motion.div 
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.6 }}
      className="w-full max-w-6xl mx-auto space-y-12 py-12 px-4"
    >
      <InvestmentVerdictCard report={report} />

      <section className="space-y-6">
        <h2 className="text-2xl font-bold tracking-tight px-2">Company Overview</h2>
        <OverviewCard data={report.companyOverview} />
      </section>

      <section className="space-y-6">
        <h2 className="text-2xl font-bold tracking-tight px-2">Financial Health</h2>
        <FinancialMetricsGrid data={report.financialSummary} />
      </section>
      
      <section className="space-y-6">
        <h2 className="text-2xl font-bold tracking-tight px-2">Recent News & Sentiment</h2>
        <NewsPanel data={report.newsSummary} />
      </section>

      <section className="space-y-6">
        <h2 className="text-2xl font-bold tracking-tight px-2">SWOT Analysis</h2>
        <SwotGrid data={report.swotAnalysis} />
      </section>

      <section className="space-y-6">
        <h2 className="text-2xl font-bold tracking-tight px-2">Risk Assessment</h2>
        <RiskPanel data={report.riskAnalysis} />
      </section>

      <section className="space-y-6">
        <h2 className="text-2xl font-bold tracking-tight px-2">Bull & Bear Cases</h2>
        <BullBearBoard report={report} />
      </section>

      <section className="border-t border-border/50 pt-8 mt-16 text-center text-sm text-muted-foreground">
        <p>Analysis generated by AI Investment Research Agent using {report.processingMetadata.model}</p>
        <p className="mt-1 opacity-70">{new Date(report.processingMetadata.timestamp).toLocaleString()}</p>
      </section>
    </motion.div>
  );
}
