"use client";

import { memo } from "react";
import { motion } from "framer-motion";
import { useResearchStore } from "@/store/useResearchStore";
import { InvestmentVerdictCard } from "./InvestmentVerdictCard";
import { OverviewCard } from "./OverviewCard";
import { FinancialMetricsGrid } from "./FinancialMetricsGrid";
import { NewsPanel } from "./NewsPanel";
import { SwotGrid } from "./SwotGrid";
import { RiskPanel } from "./RiskPanel";
import { BullBearBoard } from "./BullBearBoard";
import { ExternalLink } from "lucide-react";

/** Animated section wrapper to stagger report sections into view */
const ReportSection = memo(function ReportSection({
  id,
  title,
  delay = 0,
  children,
}: {
  id: string;
  title: string;
  delay?: number;
  children: React.ReactNode;
}) {
  return (
    <motion.section
      id={id}
      aria-labelledby={`${id}-heading`}
      initial={{ opacity: 0, y: 16 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, delay }}
      className="space-y-5"
    >
      <h2
        id={`${id}-heading`}
        className="text-xl md:text-2xl font-bold tracking-tight"
      >
        {title}
      </h2>
      {children}
    </motion.section>
  );
});

export const ReportDashboard = memo(function ReportDashboard() {
  const { report } = useResearchStore();

  if (!report) return null;

  const formattedDate = new Date(report.processingMetadata.timestamp).toLocaleString(
    undefined,
    { dateStyle: "medium", timeStyle: "short" },
  );

  return (
    <div
      className="w-full max-w-6xl mx-auto space-y-14 py-12 px-4 md:px-6"
      role="main"
      aria-label="Investment research report"
    >
      {/* ── Investment Verdict — primary focus ──────────────────────────── */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
      >
        <InvestmentVerdictCard report={report} />
      </motion.div>

      {/* ── Company Overview ──────────────────────────────────────────────── */}
      <ReportSection id="overview" title="Company Overview" delay={0.1}>
        <OverviewCard data={report.companyOverview} />
      </ReportSection>

      {/* ── Financial Health ─────────────────────────────────────────────── */}
      <ReportSection id="financials" title="Financial Health" delay={0.15}>
        <FinancialMetricsGrid data={report.financialSummary} />
      </ReportSection>

      {/* ── Recent News & Sentiment ───────────────────────────────────────── */}
      <ReportSection id="news" title="Recent News & Sentiment" delay={0.2}>
        <NewsPanel data={report.newsSummary} />
      </ReportSection>

      {/* ── SWOT Analysis ────────────────────────────────────────────────── */}
      <ReportSection id="swot" title="SWOT Analysis" delay={0.25}>
        <SwotGrid data={report.swotAnalysis} />
      </ReportSection>

      {/* ── Risk Assessment ──────────────────────────────────────────────── */}
      <ReportSection id="risks" title="Risk Assessment" delay={0.3}>
        <RiskPanel data={report.riskAnalysis} />
      </ReportSection>

      {/* ── Bull & Bear Cases ─────────────────────────────────────────────── */}
      <ReportSection id="cases" title="Bull & Bear Cases" delay={0.35}>
        <BullBearBoard report={report} />
      </ReportSection>

      {/* ── Sources ──────────────────────────────────────────────────────── */}
      {report.sources && report.sources.length > 0 && (
        <ReportSection id="sources" title="Sources" delay={0.4}>
          <ul className="space-y-2" aria-label="Data sources">
            {report.sources.map((src, i) => (
              <li key={i} className="text-sm text-muted-foreground flex items-start gap-2">
                <ExternalLink className="w-3.5 h-3.5 mt-0.5 flex-shrink-0 text-muted-foreground/60" aria-hidden="true" />
                {src.startsWith("http") ? (
                  <a
                    href={src}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="hover:text-foreground hover:underline underline-offset-4 transition-colors"
                  >
                    {src}
                  </a>
                ) : (
                  <span>{src}</span>
                )}
              </li>
            ))}
          </ul>
        </ReportSection>
      )}

      {/* ── Metadata footer ─────────────────────────────────────────────── */}
      <div className="border-t border-border/40 pt-8 text-center text-xs text-muted-foreground space-y-1">
        <p>
          Generated by AI Investment Research Agent ·{" "}
          <span className="font-mono">{report.processingMetadata.model}</span>
        </p>
        <p className="opacity-60">{formattedDate}</p>
      </div>
    </div>
  );
});
